export default {
    products: [
        {
            _id: '1',
            name:'Air Max 270',
            category:'shoes',
            image:'product_6.webp',
            price: 80,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '2',
            name:'Air Max',
            category:'shoes',
            image:'product_1.webp',
            price: 80,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '3',
            name:'Air Max',
            category:'shoes',
            image:'product_2.jpg',
            price: 80,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '4',
            name:'Air VaporMax Plus',
            category:'shoes',
            image:'product_3.webp',
            price: 220,
            brand: "Nike",
            rating:4.5,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '5',
            name:'Nike Air Max 295',
            category:'shoes',
            image:'product_4.jpg',
            price: 69,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '6',
            name:'Air Max 270',
            category:'shoes',
            image:'product_5.webp',
            price: 90,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
    ],
};