 module.exports = {
    products: [
        {
            _id: '1',
            name:'Nike Air Max',
            category:'shoes',
            image:'product_1.webp',
            price: 80,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '2',
            name:'Nike Air Max',
            category:'shoes',
            image:'product_1.webp',
            price: 80,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '3',
            name:'Nike Air Max',
            category:'shoes',
            image:'product_2.jpg',
            price: 80,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '4',
            name:'Nike Air Max',
            category:'shoes',
            image:'product_3.webp',
            price: 80,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '5',
            name:'Nike Air Max',
            category:'shoes',
            image:'product_1.webp',
            price: 80,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
        {
            _id: '6',
            name:'Nike Air Max',
            category:'shoes',
            image:'product_1.webp',
            price: 80,
            brand: "Nike",
            rating:4,
            numReviews:10,
            countInStock:5,
        },
    ],
};